#!/usr/bin/env python3
from dependency import hello

import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Test double generator mock.")
    group_req = parser.add_argument_group(title="required arguments")
    parser.add_argument("-i", "--input-header", type=str, help="Input header", required=True)
    parser.add_argument("-e", "--output-path-header", type=str, help="Output header", required=True)
    parser.add_argument("-s", "--output-path-source",help="output path source", required=True)
    parser.add_argument("-f", "--force",action="store_true",help="[Optional] force", required=False)
    parser.add_argument('-J', '--appendincludepath', action='append', default=[], help=argparse.SUPPRESS)
    args = parser.parse_args()

    f = open(args.output_path_header, "w")
    f.write("//Dummy hpp generated by test_double_generator_mock.py.\n\r")
    f.close()

    f1 = open(args.output_path_source, "w")
    f1.write("//Dummy cpp generated by test_double_generator_mock.py.\n\r")
    f1.close()

    hello()
